### ISSUE TITLE
Crash when reproducing sashimi example

### ISSUE THREAD

**Issue by ckuenne** [ygidtu/sashimi.py#58]
hi, 

this sounds like a really interesting tool that i would like to use to create sashimi plots of bam files. but i was unable to reproduce the example fig. 2a (https://github.com/ygidtu/sashimi.py/tree/main/example/Article_figures/figure2/A).

since the given gtf was not included in the repository, i replaced that with the one from ensembl (https://ftp.ensembl.org/pub/grch37/current/gtf/homo_sapiens/Homo_sapiens.GRCh37.87.chr.gtf.gz) and then ran the following command inside the figure2/A folder:
```
sashimipy \
  -e 7:107830089-107832297 \
  -r Homo_sapiens.GRCh37.87.chr.gtf.gz \
  --density bam.tsv \
  -o TNP.NRCAM.pdf \
  --dpi 300 \
  --width 6 \
  --height 1 --show-junction-num -t 10 --domain
```

resulting in the following error:
```
./run.sh
2022-12-12 15:06:25.319 | WARNING  | sashimi.cli:main:461 - Agg backend may have problems with small domain, if there is any please try cairo backend instead.
2022-12-12 15:06:25.322 | INFO     | sashimi.plot:set_region:202 - set region to 7:107830089-107832297:+
2022-12-12 15:06:25.338 | INFO     | sashimi.plot:set_reference:351 - set reference file to Homo_sapiens.GRCh37.87.chr.gtf
2022-12-12 15:06:25.346 | INFO     | sashimi.file.Reference:index_gtf:312 - Create index for Homo_sapiens.GRCh37.87.chr.gtf
[E::hts_open_format] Failed to open file "Homo_sapiens.GRCh37.87.chr.gtf.gz" : No such file or directory
2022-12-12 15:06:25.346 | ERROR    | sashimi.file.Reference:index_gtf:321 - Could not open file 'Homo_sapiens.GRCh37.87.chr.gtf.gz': No such file or directory
2022-12-12 15:06:25.346 | ERROR    | sashimi.file.Reference:index_gtf:322 - Guess gtf needs to be sorted
2022-12-12 15:06:25.347 | INFO     | sashimi.plot:plot:988 - load reference
2022-12-12 15:06:36.280 | INFO     | sashimi.plot:plot:1002 - load data of 12 plots
2022-12-12 15:06:36.280 | INFO     | sashimi.plot:plot:1039 - init graph_coords
Traceback (most recent call last):
  File "/mnt/software/x86_64/packages/python/3.9.0-miniconda-4.12.0-bullseye/bin/sashimipy", line 8, in <module>
    sys.exit(main())
  File "/mnt/software/x86_64/packages/python/3.9.0-miniconda-4.12.0-bullseye/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/software/x86_64/packages/python/3.9.0-miniconda-4.12.0-bullseye/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/mnt/software/x86_64/packages/python/3.9.0-miniconda-4.12.0-bullseye/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/software/x86_64/packages/python/3.9.0-miniconda-4.12.0-bullseye/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/software/x86_64/packages/python/3.9.0-miniconda-4.12.0-bullseye/lib/python3.9/site-packages/sashimi/cli.py", line 727, in main
    p.plot(
  File "/mnt/software/x86_64/packages/python/3.9.0-miniconda-4.12.0-bullseye/lib/python3.9/site-packages/sashimi/plot.py", line 1081, in plot
    plot_density(
  File "/mnt/software/x86_64/packages/python/3.9.0-miniconda-4.12.0-bullseye/lib/python3.9/site-packages/sashimi/plot_func.py", line 634, in plot_density
    assert obj.region is not None, "please load data first"
AssertionError: please load data first
```

this is running on debian 11.5 (bullseye) with python 3.9.0-miniconda-4.12.0. i installed the package with pip, which ran without problems. any idea what's going wrong?

**Comment by ygidtu** [comment]
Hi ckuenne,
    Sorry for the inconvenience, I made a mistake while merge development code in version 0.0.9, I fixed it and release an new version 0.1.0, please update and try
Best wishes,
Yiming Zhang
